### PR TITLE
Allows botty to read notes using just the note name (ex: !repo)

### PR DESCRIPTION
**Pull request by s-coimbra21**

### CODE REVIEW

**Comment by Querijn** [comment]
Might conflict with other functionality.. It was kind of setup this way on purpose

**Comment by s-coimbra21** [comment]
Yes, ideally, all the builtin commands would be stored as constants in some file and those would be read to disallow already existing commands from being added by `!note add ${cmd}`. But right now only admins can add commands so its not that big of a deal.

**Comment by Querijn** [comment]
You're forgetting we have Derp as admin

**Comment by s-coimbra21** [comment]
`helpers/isDerp.ts`

**Comment by Querijn** [comment]
Thanks!

**Pull request merged**
