### PR TITLE
Add event handler

### PR DESCRIPTION
**Pull request by stelar7**
Should prevent the following message from being shown in console as we avoid calling .on()
>(node) warning: possible EventEmitter memory leak detected. 11 change listeners added. Use emitter.setMaxListeners() to increase limit.

Also avoids adding `bot` to every constructor..

### CODE REVIEW

**Comment by Querijn** [comment]
We could also call emitter.setMaxListeners...

**Comment by stelar7** [comment]
:thinking:

**Comment by Querijn** [comment]
Let's not make a giant overhaul because of a warning message..

**Comment by stelar7** [comment]
I mean.. The overhaul is already done..

**Comment by Querijn** [comment]
The main issue is, I have the responsibility of maintaining this after this PR. Maybe someone else takes over, and they have to. The added complexicity is just not worth the added cost to maintainability. I would much rather have a single call to client.setMaxListeners than this.

Not to demotivate you from doing this, I love the effort you put into this project, but let's discuss the things beforehand, or make an issue about them, this opens a discussion before I'd have to look through 300 changes. I really dislike closing this because a lot of effort went into it of course. I'm sorry.

**Pull request closed without merging**
