### PR TITLE
Use evenin to detect greetings

### PR DESCRIPTION
**Pull request by molenzwiebel**
Got tired of having a hardcoded list of greetings for only a certain amount of languages. Now uses [evenin](https://github.com/molenzwiebel/evenin), which supports slightly more phrases.

If we're interested, might also add a command to look up what a greeting means.

Also we should probably have a blacklist for some greetings since I assume that some are going to get very annoying very fast.

<3

### CODE REVIEW

**Comment by Querijn** [comment]
The type definitions are missing from the package, at least when I install it

**Comment by Querijn** [comment]
hasGreeting doesn't work in cases where the words aren't split up by spaces, needs punctuation as well.

**Comment by Querijn** [comment]
Alright, I've tested it enough, it works but evenin needs a couple of changes. I'm going to make a PR for the last issue.

**Comment by Azoy** [comment]
smh

**Pull request merged**
