### PR TITLE
fix notes not showing up in the list

### LINKED ISSUE #109: Newly added notes won't be in !note list
This is because the old emojis are listed like `<emoji:id>` while newly-added ones are stored as `id`

### PR DESCRIPTION
**Pull request by stelar7**
fixes #109

### CODE REVIEW

**Comment by Querijn** [comment]
nice, was looking forward to this one

**Comment by stelar7** [comment]
it works for me 🤷‍♂️ the id seems to always be null

**Comment by Querijn** [comment]
Maybe because it needs to be fetched.. In that case, it can be removed altogether, I assume?

**Comment by stelar7** [comment]
Dont know, havent tested that

**Comment by Querijn** [comment]
If you could confirm, that would be amazing, and I could upload a new version of Botty today

**Pull request closed without merging**
